### ISSUE TITLE
Unable to find repository | joinflux/firebase-action

### ISSUE THREAD

**Issue by davidanrod** [joinflux/firebase-tools#3]
Hi,

probably it's not related to the repo itself, but right now, can't run this action with the following error:

**Unable to resolve actions. Repository not found : joinflux/firebase-action**.

- name: Deploy to Firebase
        uses: joinflux/firebase-action@9.16.0
        with:
          args: deploy --project=frontoffice --only hosting:mpro-frontoffice-index-dev
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

i've tried to change @master to a specific version of: @9.16.0 but same problem..
Are this related somehow to github actions?

Best,
David.

**Comment by davidanrod** [comment]
Ok, after some tests, i've just realize that somehow the action name does not point to the right place...

there are mismatch between **firebase-tools** and **firebase-action** maybe due to a repo rename or something weird...

Anyway, the correct fix for that is to invoke **joinflux/firebase-tools@master** instead of **joinflux/firebase-action@master** 

Best,
David.

**Comment by gugahoi** [comment]
> Ok, after some tests, i've just realize that somehow the action name does not point to the right place...
> 
> there are mismatch between **firebase-tools** and **firebase-action** maybe due to a repo rename or something weird...
> 
> Anyway, the correct fix for that is to invoke **joinflux/firebase-tools@master** instead of **joinflux/firebase-action@master**
> 
> Best, David.

Sorry about that David. I need to make the name of the action more explicit in the docs. You might be able to see the correct name in the example in the README right now but it is definitely not obvious.

**Comment by gugahoi** [comment]
Appologies, I misunderstood what you meant and you are correct that this repo was renamed. I have created a PR to update the docs with the correct documentation. Please feel free to give any feedback on it if you'd like.
